---
header-includes: 
  - \input{preamble.tex}
latex_engine: xelatex
fontsize: 9.5pt
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
sansfont: Lato
font: Lato
geometry: left=0.65in,right=0.65in,top=0.35in,bottom=0.5in
urlcolor: null
---

\raggedright

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r rmarkdown-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(dev = "cairo_pdf")

library(data.table)
library(flextable)
library(ggmap)
library(ggrepel)
library(glue)
library(gt)
library(janitor)
library(knitr)
library(kableExtra)
library(lubridate)
library(osmdata)
library(readxl)
library(scales)
library(sf)
library(sp)
library(tidycensus)
library(tidyverse)
library(tigris)
library(tinytex)
library(urbnmapr)
library(urbnthemes)
library(zoo)
```

```{r}
city_title <- c("Memphis")
city_name <- c("Memphis","memphis")
city_name_state <- c("Memphis, TN")
city_state <- c("TN")
city_df <- c("memphis_city")
city_title_df <- c("City of Memphis")
city_dis_title_df <- c("Memphis city")

msa_name <- c("Memphis-","memphis-")
msa_state <- c("Tennessee")
msa_df <- c("memphis_msa")
msa_title_df <- c("Memphis MSA")

msa_md_code <- c("32820|47664")
state_df <- c("47")
```


```{r include = FALSE}
# label/table functions
percentLabel <- function(x, digits = 1, format = "f", ...) {
  paste0(formatC(100 * x, format = format, digits = digits, ...), "%")
}

dollarLabel <- function(x, ...) {
  paste0("$", x, ...)
}

dollarLabel_k <- function(x, ...) {
  paste0("$", x, "k", ...)
}
```

```{r}
xwalk_hhwt_df <- fread("data/memphis/geocorr2018_tn2016_hhwt.csv") %>% 
  janitor::clean_names() %>%
  dplyr::rename(puma_name = pum_aname) %>% 
  dplyr::mutate(memphis_city_place = if_else(str_detect(placenm14, "Memphis city"), "1", "0")) %>%
  dplyr::filter(memphis_city_place == "1") %>% 
  dplyr::select(puma, hh_afact_2016) %>%
  dplyr::rename(hh_afact = hh_afact_2016)
  
xwalk_df <- fread("data/memphis/geocorr2018_tn2016.csv") %>% 
  janitor::clean_names() %>%
  dplyr::mutate(memphis_city_place = if_else(str_detect(placenm14, "Memphis city"), "1", "0")) %>%
  dplyr::filter(memphis_city_place == "1") %>% 
  dplyr::select(puma, afact_2016) %>%
  dplyr::rename(afact = afact_2016) %>%
  dplyr::left_join(xwalk_hhwt_df, by = "puma") 
  
glimpse(xwalk_df)
```

```{r include = FALSE}
# acs data
acs_hh_2009 <- fread("data/usa_2009.csv.gz")
acs_hh_2014 <- fread("data/usa_2014.csv.gz")
acs_hh_2019 <- fread("data/usa_2019.csv.gz")

acs_hh_df <- bind_rows(acs_hh_2009, acs_hh_2014, acs_hh_2019) 
```

```{r}
acs_hh <- acs_hh_df %>%
  clean_names() %>%
  dplyr::filter(pernum == 1) %>%
  dplyr::filter(gq != 3 & gq != 4) %>%
  dplyr::mutate(columbus_msa = if_else(met2013 == "18140", "1", "0"),
                detroit_msa = if_else(met2013 == "19820", "1", "0"),
                memphis_msa = if_else(met2013 == "32820", "1", "0"),
                
                detroit_city = if_else(city == "1750", "1", "0"),
                
                memphis_city = if_else(city == "4010", "1", "0"),
                
                memphis_puma = case_when(puma == 3201 ~ "1",
                                         puma == 3202 ~ "1",
                                         puma == 3203 ~ "1",
                                         puma == 3204 ~ "1",
                                         puma == 3205 ~ "1",
                                         puma == 3206 ~ "1",
                                         puma == 3207 ~ "1",
                                         puma == 3208 ~ "1",
                                         TRUE ~ as.character("0")),
                
                columbus_city = case_when(puma == 3900 ~ "1",
                                          puma == 4000 ~ "1",
                                          puma == 4101 ~ "1",
                                          puma == 4102 ~ "1",
                                          puma == 4103 ~ "1",
                                          puma == 4104 ~ "1",
                                          puma == 4105 ~ "1",
                                          puma == 4106 ~ "1",
                                          puma == 4107 ~ "1",
                                          puma == 4108 ~ "1",
                                          puma == 4109 ~ "1",
                                          puma == 4110 ~ "1",
                                          puma == 4111 ~ "1",
                                          TRUE ~ as.character("0"))) %>%
  
  dplyr::mutate(acs_year = factor(case_when(year == 2009 ~ "2005–09", 
                                            year == 2014 ~ "2010–14",
                                            year == 2019 ~ "2015–19"),
                                  levels = c("2005–09", "2010–14", "2015–19")),
                
                own = if_else(ownershp == 1, "Owners", "Renters"),
                
                raceeth = factor(case_when(race == 1 & hispan==0 ~ 'White',
                                            race == 2 & hispan==0 ~ 'Black',
                                            race >= 4 & race <= 6 & hispan==0 ~ 'Asian',
                                            hispan !=0 ~ 'Hispanic',
                                           TRUE ~ as.character("Other")),
                                  levels = c("Asian", "Black", "Hispanic", "White", "Other")),
                
                type = factor(case_when(unitsstr == 1 ~ "Mobile home",
                                        unitsstr == 4 ~ "Attached single-family home",
                                        unitsstr == 3 ~ "Detached single-family home",
                                        unitsstr == 5 ~ "2-to-4-unit multifamily home",
                                        unitsstr == 6 ~ "2-to-4-unit multifamily home",
                                        unitsstr == 7 ~ "5-to-19-unit multifamily home",
                                        unitsstr == 8 ~ "5-to-19-unit multifamily home",
                                        unitsstr == 9 ~ "20-to-49-unit multifamily home",
                                        unitsstr == 10 ~ "50-or-more-unit multifamily home"),
                       levels = c("Mobile home", "Attached single-family home", "Detached single-family home",
                                  "2-to-4-unit multifamily home", "5-to-19-unit multifamily home",
                                  "20-to-49-unit multifamily home", "50-or-more-unit multifamily home")),
                
                age = factor(case_when(builtyr2 == 1 ~ "Before 1940",
                                       builtyr2 == 2 ~ "1940–1959",
                                       builtyr2 == 3 ~ "1940–1959",
                                       builtyr2 == 4 ~ "1960–1979",
                                       builtyr2 == 5 ~ "1960–1979",
                                       builtyr2 == 6 ~ "1980–1999",
                                       builtyr2 == 7 ~ "1980–1999",
                                       builtyr2 == 8 ~ "1980–1999",
                                       builtyr2 >= 9 & builtyr2 < 15 ~ "2000–2009",
                                       builtyr2 >= 15 ~ "Since 2010"),
                             levels = c("Before 1940","1940–1959","1960–1979","1980–1999","2000–2009","Since 2010")),
                
                hhincome = na_if(hhincome, 9999999),
  
                adjhhinc = case_when(year == 2009 ~ hhincome*255.657/214.537,
                                     year == 2014 ~ hhincome*255.657/237.017,
                                     TRUE ~ as.double(hhincome)),
                
                rentgrs = na_if(rentgrs, 9999999),
                
                adjrent = case_when(year == 2009 ~ rentgrs*255.657/214.537,
                                    year == 2014 ~ rentgrs*255.657/237.017,
                                    TRUE ~ as.double(rentgrs)),
                
                valueh = na_if(valueh, 9999999),
                adjhv = case_when(year == 2009 ~ valueh*255.657/214.537,
                                  year == 2014 ~ valueh*255.657/237.017,
                                  TRUE ~ as.double(valueh)),
                
                rentburden = if_else((rentgrs*12)/hhincome>0.3 & own == "Renters", 1, 0),
                ownburden = if_else((owncost*12)/hhincome>0.3 & own == "Owners", 1, 0)) %>%
  dplyr::select(-columbus_city, -columbus_msa, -detroit_city, -detroit_msa)

acs_hh_city <- acs_hh %>%
  dplyr::filter(statefip == state_df) %>%
  dplyr::filter(memphis_puma == "1") %>%
  dplyr::right_join(xwalk_df, by = "puma") %>%
  dplyr::mutate(perwt_adj = perwt*afact,
                hhwt_adj = hhwt*hh_afact)
```
